// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.3
// source: settle/service/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BizType int32

const (
	BizType_BizTypeUnknown BizType = 0
	BizType_BizTypeRental  BizType = 1
	BizType_BizTypeHotel   BizType = 2
	BizType_BizTypeTrain   BizType = 3
	BizType_BizTypeFlight  BizType = 4
)

// Enum value maps for BizType.
var (
	BizType_name = map[int32]string{
		0: "BizTypeUnknown",
		1: "BizTypeRental",
		2: "BizTypeHotel",
		3: "BizTypeTrain",
		4: "BizTypeFlight",
	}
	BizType_value = map[string]int32{
		"BizTypeUnknown": 0,
		"BizTypeRental":  1,
		"BizTypeHotel":   2,
		"BizTypeTrain":   3,
		"BizTypeFlight":  4,
	}
)

func (x BizType) Enum() *BizType {
	p := new(BizType)
	*p = x
	return p
}

func (x BizType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizType) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_service_v1_common_proto_enumTypes[0].Descriptor()
}

func (BizType) Type() protoreflect.EnumType {
	return &file_settle_service_v1_common_proto_enumTypes[0]
}

func (x BizType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizType.Descriptor instead.
func (BizType) EnumDescriptor() ([]byte, []int) {
	return file_settle_service_v1_common_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_OrderTypeUnknown   OrderType = 0
	OrderType_OrderTypeNormal    OrderType = 1
	OrderType_OrderTypeReplenish OrderType = 2
	OrderType_OrderTypeRenewal   OrderType = 3
	OrderType_OrderTypeModify    OrderType = 4
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "OrderTypeUnknown",
		1: "OrderTypeNormal",
		2: "OrderTypeReplenish",
		3: "OrderTypeRenewal",
		4: "OrderTypeModify",
	}
	OrderType_value = map[string]int32{
		"OrderTypeUnknown":   0,
		"OrderTypeNormal":    1,
		"OrderTypeReplenish": 2,
		"OrderTypeRenewal":   3,
		"OrderTypeModify":    4,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_service_v1_common_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_settle_service_v1_common_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_settle_service_v1_common_proto_rawDescGZIP(), []int{1}
}

type RefundType int32

const (
	RefundType_RefundTypeUnknown    RefundType = 0
	RefundType_RefundTypeSource     RefundType = 1
	RefundType_RefundTypeEnergy     RefundType = 2
	RefundType_RefundTypeUserCancel RefundType = 3
	RefundType_RefundTypePenalty    RefundType = 4
)

// Enum value maps for RefundType.
var (
	RefundType_name = map[int32]string{
		0: "RefundTypeUnknown",
		1: "RefundTypeSource",
		2: "RefundTypeEnergy",
		3: "RefundTypeUserCancel",
		4: "RefundTypePenalty",
	}
	RefundType_value = map[string]int32{
		"RefundTypeUnknown":    0,
		"RefundTypeSource":     1,
		"RefundTypeEnergy":     2,
		"RefundTypeUserCancel": 3,
		"RefundTypePenalty":    4,
	}
)

func (x RefundType) Enum() *RefundType {
	p := new(RefundType)
	*p = x
	return p
}

func (x RefundType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundType) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_service_v1_common_proto_enumTypes[2].Descriptor()
}

func (RefundType) Type() protoreflect.EnumType {
	return &file_settle_service_v1_common_proto_enumTypes[2]
}

func (x RefundType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundType.Descriptor instead.
func (RefundType) EnumDescriptor() ([]byte, []int) {
	return file_settle_service_v1_common_proto_rawDescGZIP(), []int{2}
}

type SettleType int32

const (
	SettleType_SettleTypeUnknown SettleType = 0
	SettleType_SettleTypeNormal  SettleType = 1
	SettleType_SettleTypeMerge   SettleType = 2
	SettleType_SettleTypeGoods   SettleType = 3
	SettleType_SettleTypeSublet  SettleType = 4
)

// Enum value maps for SettleType.
var (
	SettleType_name = map[int32]string{
		0: "SettleTypeUnknown",
		1: "SettleTypeNormal",
		2: "SettleTypeMerge",
		3: "SettleTypeGoods",
		4: "SettleTypeSublet",
	}
	SettleType_value = map[string]int32{
		"SettleTypeUnknown": 0,
		"SettleTypeNormal":  1,
		"SettleTypeMerge":   2,
		"SettleTypeGoods":   3,
		"SettleTypeSublet":  4,
	}
)

func (x SettleType) Enum() *SettleType {
	p := new(SettleType)
	*p = x
	return p
}

func (x SettleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettleType) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_service_v1_common_proto_enumTypes[3].Descriptor()
}

func (SettleType) Type() protoreflect.EnumType {
	return &file_settle_service_v1_common_proto_enumTypes[3]
}

func (x SettleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettleType.Descriptor instead.
func (SettleType) EnumDescriptor() ([]byte, []int) {
	return file_settle_service_v1_common_proto_rawDescGZIP(), []int{3}
}

var File_settle_service_v1_common_proto protoreflect.FileDescriptor

var file_settle_service_v1_common_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2a, 0x67, 0x0a, 0x07, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x0e, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x6f, 0x74, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x69, 0x7a, 0x54, 0x79,
	0x70, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x69, 0x7a,
	0x54, 0x79, 0x70, 0x65, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x10, 0x04, 0x2a, 0x79, 0x0a, 0x09,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c,
	0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x10, 0x04, 0x2a, 0x80, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x50, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x10, 0x04, 0x2a, 0x79, 0x0a, 0x0a, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x10, 0x03, 0x12,
	0x14, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x62,
	0x6c, 0x65, 0x74, 0x10, 0x04, 0x42, 0x1a, 0x5a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settle_service_v1_common_proto_rawDescOnce sync.Once
	file_settle_service_v1_common_proto_rawDescData = file_settle_service_v1_common_proto_rawDesc
)

func file_settle_service_v1_common_proto_rawDescGZIP() []byte {
	file_settle_service_v1_common_proto_rawDescOnce.Do(func() {
		file_settle_service_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_settle_service_v1_common_proto_rawDescData)
	})
	return file_settle_service_v1_common_proto_rawDescData
}

var file_settle_service_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_settle_service_v1_common_proto_goTypes = []interface{}{
	(BizType)(0),    // 0: settle.service.v1.BizType
	(OrderType)(0),  // 1: settle.service.v1.OrderType
	(RefundType)(0), // 2: settle.service.v1.RefundType
	(SettleType)(0), // 3: settle.service.v1.SettleType
}
var file_settle_service_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settle_service_v1_common_proto_init() }
func file_settle_service_v1_common_proto_init() {
	if File_settle_service_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settle_service_v1_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settle_service_v1_common_proto_goTypes,
		DependencyIndexes: file_settle_service_v1_common_proto_depIdxs,
		EnumInfos:         file_settle_service_v1_common_proto_enumTypes,
	}.Build()
	File_settle_service_v1_common_proto = out.File
	file_settle_service_v1_common_proto_rawDesc = nil
	file_settle_service_v1_common_proto_goTypes = nil
	file_settle_service_v1_common_proto_depIdxs = nil
}
