// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.3
// source: settle/service/v1/create.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BizType          BizType   `protobuf:"varint,1,opt,name=biz_type,json=bizType,proto3,enum=settle.service.v1.BizType" json:"biz_type,omitempty"`
	Uid              int64     `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	OrderId          int64     `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SubOrderId       int64     `protobuf:"varint,4,opt,name=sub_order_id,json=subOrderId,proto3" json:"sub_order_id,omitempty"`
	Source           int32     `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`
	SupplierCode     string    `protobuf:"bytes,6,opt,name=supplier_code,json=supplierCode,proto3" json:"supplier_code,omitempty"`
	SotreAmount      int64     `protobuf:"varint,7,opt,name=sotre_amount,json=sotreAmount,proto3" json:"sotre_amount,omitempty"`
	TargetAmount     int64     `protobuf:"varint,8,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`
	RealPayAmount    int64     `protobuf:"varint,9,opt,name=real_pay_amount,json=realPayAmount,proto3" json:"real_pay_amount,omitempty"`
	CouponAmount     int64     `protobuf:"varint,10,opt,name=coupon_amount,json=couponAmount,proto3" json:"coupon_amount,omitempty"`
	PromotionAmount  int64     `protobuf:"varint,11,opt,name=promotion_amount,json=promotionAmount,proto3" json:"promotion_amount,omitempty"`
	MerchantDiscount int64     `protobuf:"varint,12,opt,name=merchant_discount,json=merchantDiscount,proto3" json:"merchant_discount,omitempty"`
	OrderType        OrderType `protobuf:"varint,13,opt,name=order_type,json=orderType,proto3,enum=settle.service.v1.OrderType" json:"order_type,omitempty"`
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_service_v1_create_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settle_service_v1_create_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_settle_service_v1_create_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetBizType() BizType {
	if x != nil {
		return x.BizType
	}
	return BizType_BizTypeUnknown
}

func (x *CreateOrderRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderRequest) GetSubOrderId() int64 {
	if x != nil {
		return x.SubOrderId
	}
	return 0
}

func (x *CreateOrderRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *CreateOrderRequest) GetSupplierCode() string {
	if x != nil {
		return x.SupplierCode
	}
	return ""
}

func (x *CreateOrderRequest) GetSotreAmount() int64 {
	if x != nil {
		return x.SotreAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetRealPayAmount() int64 {
	if x != nil {
		return x.RealPayAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetCouponAmount() int64 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetPromotionAmount() int64 {
	if x != nil {
		return x.PromotionAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetMerchantDiscount() int64 {
	if x != nil {
		return x.MerchantDiscount
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_OrderTypeUnknown
}

type PayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutTradeId string `protobuf:"bytes,1,opt,name=out_trade_id,json=outTradeId,proto3" json:"out_trade_id,omitempty"`
}

func (x *PayInfo) Reset() {
	*x = PayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_service_v1_create_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayInfo) ProtoMessage() {}

func (x *PayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_settle_service_v1_create_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayInfo.ProtoReflect.Descriptor instead.
func (*PayInfo) Descriptor() ([]byte, []int) {
	return file_settle_service_v1_create_proto_rawDescGZIP(), []int{1}
}

func (x *PayInfo) GetOutTradeId() string {
	if x != nil {
		return x.OutTradeId
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayInfo *PayInfo `protobuf:"bytes,1,opt,name=pay_info,json=payInfo,proto3" json:"pay_info,omitempty"`
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_service_v1_create_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settle_service_v1_create_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_settle_service_v1_create_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetPayInfo() *PayInfo {
	if x != nil {
		return x.PayInfo
	}
	return nil
}

var File_settle_service_v1_create_proto protoreflect.FileDescriptor

var file_settle_service_v1_create_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x81, 0x04, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x08, 0x62, 0x69,
	0x7a, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x62, 0x69, 0x7a, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x6f, 0x74, 0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x6f, 0x74, 0x72, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x70, 0x61,
	0x79, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x72, 0x65, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a,
	0x11, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x70,
	0x61, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x61, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x42, 0x1a, 0x5a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settle_service_v1_create_proto_rawDescOnce sync.Once
	file_settle_service_v1_create_proto_rawDescData = file_settle_service_v1_create_proto_rawDesc
)

func file_settle_service_v1_create_proto_rawDescGZIP() []byte {
	file_settle_service_v1_create_proto_rawDescOnce.Do(func() {
		file_settle_service_v1_create_proto_rawDescData = protoimpl.X.CompressGZIP(file_settle_service_v1_create_proto_rawDescData)
	})
	return file_settle_service_v1_create_proto_rawDescData
}

var file_settle_service_v1_create_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_settle_service_v1_create_proto_goTypes = []interface{}{
	(*CreateOrderRequest)(nil),  // 0: settle.service.v1.CreateOrderRequest
	(*PayInfo)(nil),             // 1: settle.service.v1.PayInfo
	(*CreateOrderResponse)(nil), // 2: settle.service.v1.CreateOrderResponse
	(BizType)(0),                // 3: settle.service.v1.BizType
	(OrderType)(0),              // 4: settle.service.v1.OrderType
}
var file_settle_service_v1_create_proto_depIdxs = []int32{
	3, // 0: settle.service.v1.CreateOrderRequest.biz_type:type_name -> settle.service.v1.BizType
	4, // 1: settle.service.v1.CreateOrderRequest.order_type:type_name -> settle.service.v1.OrderType
	1, // 2: settle.service.v1.CreateOrderResponse.pay_info:type_name -> settle.service.v1.PayInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_settle_service_v1_create_proto_init() }
func file_settle_service_v1_create_proto_init() {
	if File_settle_service_v1_create_proto != nil {
		return
	}
	file_settle_service_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_settle_service_v1_create_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_service_v1_create_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_service_v1_create_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settle_service_v1_create_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settle_service_v1_create_proto_goTypes,
		DependencyIndexes: file_settle_service_v1_create_proto_depIdxs,
		MessageInfos:      file_settle_service_v1_create_proto_msgTypes,
	}.Build()
	File_settle_service_v1_create_proto = out.File
	file_settle_service_v1_create_proto_rawDesc = nil
	file_settle_service_v1_create_proto_goTypes = nil
	file_settle_service_v1_create_proto_depIdxs = nil
}
