// protoc -I=/Users/didi/vscode/x-finance/api --go_out=. --go-grpc_out=. settle/service/v1/common.proto settle/service/v1/create.proto settle/service/v1/cancel.proto settle/service/v1/refund.proto settle/service/v1/settle.proto settle/service/v1/service.proto

syntax = "proto3";

package settle.service.v1;

option go_package = "api/settle/service/v1;v1";

import "google/protobuf/empty.proto";
import "settle/service/v1/create.proto";
import "settle/service/v1/cancel.proto";
import "settle/service/v1/refund.proto";
import "settle/service/v1/settle.proto";

service SettleSvc {
    // order
    rpc OrderCreate(CreateOrderRequest) returns (CreateOrderResponse);
    rpc OrderCancel(CancelRequest) returns (CancelResponse);
    rpc OrderRefund(RefundRequest) returns (RefundResponse);
    rpc OrderSettle(SettleRequest) returns (google.protobuf.Empty);

    // deposit
    // rpc DeductRefund(DeductRefundRequest) returns (google.protobuf.Empty);
}