// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.3
// source: settle/service/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SettleSvcClient is the client API for SettleSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettleSvcClient interface {
	// order
	OrderCreate(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	OrderCancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	OrderRefund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
	OrderSettle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type settleSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewSettleSvcClient(cc grpc.ClientConnInterface) SettleSvcClient {
	return &settleSvcClient{cc}
}

func (c *settleSvcClient) OrderCreate(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/settle.service.v1.SettleSvc/OrderCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleSvcClient) OrderCancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, "/settle.service.v1.SettleSvc/OrderCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleSvcClient) OrderRefund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, "/settle.service.v1.SettleSvc/OrderRefund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settleSvcClient) OrderSettle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/settle.service.v1.SettleSvc/OrderSettle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettleSvcServer is the server API for SettleSvc service.
// All implementations must embed UnimplementedSettleSvcServer
// for forward compatibility
type SettleSvcServer interface {
	// order
	OrderCreate(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	OrderCancel(context.Context, *CancelRequest) (*CancelResponse, error)
	OrderRefund(context.Context, *RefundRequest) (*RefundResponse, error)
	OrderSettle(context.Context, *SettleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSettleSvcServer()
}

// UnimplementedSettleSvcServer must be embedded to have forward compatible implementations.
type UnimplementedSettleSvcServer struct {
}

func (UnimplementedSettleSvcServer) OrderCreate(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderCreate not implemented")
}
func (UnimplementedSettleSvcServer) OrderCancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderCancel not implemented")
}
func (UnimplementedSettleSvcServer) OrderRefund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderRefund not implemented")
}
func (UnimplementedSettleSvcServer) OrderSettle(context.Context, *SettleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderSettle not implemented")
}
func (UnimplementedSettleSvcServer) mustEmbedUnimplementedSettleSvcServer() {}

// UnsafeSettleSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettleSvcServer will
// result in compilation errors.
type UnsafeSettleSvcServer interface {
	mustEmbedUnimplementedSettleSvcServer()
}

func RegisterSettleSvcServer(s grpc.ServiceRegistrar, srv SettleSvcServer) {
	s.RegisterService(&SettleSvc_ServiceDesc, srv)
}

func _SettleSvc_OrderCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleSvcServer).OrderCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settle.service.v1.SettleSvc/OrderCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleSvcServer).OrderCreate(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettleSvc_OrderCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleSvcServer).OrderCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settle.service.v1.SettleSvc/OrderCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleSvcServer).OrderCancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettleSvc_OrderRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleSvcServer).OrderRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settle.service.v1.SettleSvc/OrderRefund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleSvcServer).OrderRefund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettleSvc_OrderSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettleSvcServer).OrderSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/settle.service.v1.SettleSvc/OrderSettle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettleSvcServer).OrderSettle(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettleSvc_ServiceDesc is the grpc.ServiceDesc for SettleSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettleSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settle.service.v1.SettleSvc",
	HandlerType: (*SettleSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderCreate",
			Handler:    _SettleSvc_OrderCreate_Handler,
		},
		{
			MethodName: "OrderCancel",
			Handler:    _SettleSvc_OrderCancel_Handler,
		},
		{
			MethodName: "OrderRefund",
			Handler:    _SettleSvc_OrderRefund_Handler,
		},
		{
			MethodName: "OrderSettle",
			Handler:    _SettleSvc_OrderSettle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "settle/service/v1/service.proto",
}
