CREATE TABLE `orders` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `uid` bigint unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
    `source` int unsigned NOT NULL DEFAULT '0' COMMENT '服务商id 1:携程 2:悟空 3:哈罗 4:飞猪',
    `supplier_code` varchar(128) NOT NULL DEFAULT '' COMMENT '供应商ID',
    `merchant_code` varchar(128) NOT NULL DEFAULT '' COMMENT '转租商ID',
    `relate_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '主订单编号',
    `relate_sub_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '子订单编号',
    `third_order_id` varchar(128) DEFAULT NULL COMMENT '第三方订单编号',
    `third_sub_order_id` varchar(128) NOT NULL DEFAULT '' COMMENT '服务商子订单id',
    `order_type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '订单类型',
    `third_store_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '商家优惠前价格',
    `target_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '结算价',
    `real_pay_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '实际支付金额',
    `coupon_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '优惠券抵扣金额',
    `promotion_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '平台优惠金额',
    `merchant_discount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '商家优惠金额',
    `coupon_info` json NOT NULL DEFAULT '{}' COMMENT '优惠券信息',
    `pay_status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '支付状态 0:待支付 1:已支付 3:已取消',
    `pay_id` varchar(128) NOT NULL DEFAULT '' COMMENT '收银台支付id 对应收银台out_trade_id',
    `trade_id` varchar(128) NOT NULL DEFAULT '' COMMENT '收银台交易单号 对应收银台trade_id',
    `pay_channel_id` int unsigned NOT NULL DEFAULT '0' COMMENT '支付渠道id',
    `paid_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '支付时间',
    `settle_status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '分账状态 0:未分账 1:分账中 2:已分账 3:分账失败',
    `settle_detail` json NOT NULL DEFAULT '{}' COMMENT '分账详情',
    `settled_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '分账时间',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_order_id` (`relate_order_id`, `relate_sub_order_id`),
    KEY `idx_uid` (`uid`),
    KEY `idx_sub_order_id` (`relate_sub_order_id`),
    KEY `idx_third_order_id` (`third_order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 CHARSET = utf8mb4 COMMENT = '子订单表';

CREATE TABLE `order_settle_details` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
    `relate_sub_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '子订单编号',
    `target_type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '分账对象类型: 0:平台 1:商户 2:三方',
    `merchant_id` varchar(64) NOT NULL DEFAULT '' COMMENT '商户号id',
    `settle_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '分账金额',
    `actual_settle_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '实际分账金额',
    `commission_rate` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '分账比例',
    `initiate_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '分账发起时间',
    `complete_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '分账完成时间',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`relate_sub_order_id`),
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '订单分账明细表';

CREATE TABLE `refunds` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
    `relate_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '主订单编号',
    `relate_sub_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '子订单编号',
    `third_refund_no` varchar(128) NOT NULL DEFAULT '' COMMENT '第三方退款单号',
    `deduct_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '扣款金额',
    `refund_no` varchar(128) NOT NULL COMMENT '退款单号',
    `refund_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '通知退款金额',
    `refund_real` bigint unsigned NOT NULL DEFAULT 0 COMMENT '退款金额',
    `refund_coupon` bigint unsigned NOT NULL DEFAULT 0 COMMENT '退券金额',
    `refund_promotion` bigint unsigned NOT NULL DEFAULT 0 COMMENT '退平台优惠金额',
    `refund_status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '退款状态',
    `refund_type` int unsigned NOT NULL DEFAULT 0 COMMENT '退款类型',
    `refund_reason` varchar(1024) DEFAULT NULL COMMENT '退款原因',
    `refund_detail` json NOT NULL DEFAULT '{}' COMMENT '退款详情',
    `refund_after_settle` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否分账后退款 0:否 1:是',
    `coupon_compensate` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '是否退券, 0:否, 1:是',
    `initiate_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '退款发起时间',
    `complete_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '退款完成时间',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_refund_no` (`refund_no`),
    KEY `idx_order_id` (`relate_order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '退款主表';

CREATE TABLE `refund_settle_details` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
    `relate_sub_order_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '子订单编号',
    `refund_no` varchar(128) NOT NULL COMMENT '退款单号',
    `target_type` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '分账对象类型: 0:平台 1:商户 2:三方',
    `merchant_id` varchar(64) NOT NULL DEFAULT '' COMMENT '商户号id',
    `grant_merchant_id` varchar(64) NOT NULL DEFAULT '' COMMENT '代发商户号id'
    `refund_amount` bigint unsigned NOT NULL DEFAULT 0 COMMENT '退款金额',
    `refund_status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '退款状态',
    `refund_time` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01' COMMENT '退款时间',
    `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_refund_no` (`refund_no`),
    KEY `idx_order_id` (`relate_sub_order_id`),
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '退款分账明细表';
